from langchain_core.tools import tool
from langchain_pinecone import PineconeVectorStore
from langchain_google_genai import GoogleGenerativeAIEmbeddings
from pinecone import Pinecone
from dotenv import load_dotenv
from utils.connections import get_db_connection
import os

load_dotenv()

GOOGLE_API_KEY = os.getenv('GOOGLE_API_KEY')

embeddings = GoogleGenerativeAIEmbeddings(
    model="gemini-embedding-001",
    google_api_key=os.getenv("GOOGLE_API_KEY"),
    output_dimensions=3072
)

pc = Pinecone(api_key=os.getenv("PINECONE_API_KEY"))
index = pc.Index(os.getenv("INDEX_NAME"))

vectorstore = PineconeVectorStore(
    index=index,
    embedding=embeddings
)

@tool
def get_schema(query: str) -> list:
    """
    Tool for fetching database schema from the Pinecone vector database

    Args:
        query: User query to retrieve the vectors
    
    Returns:
        List of database schema required to generate SQL query, or returns error message. 
    """
    try:
        raw_context = vectorstore.similarity_search_with_relevance_scores(query=query, k=5)
        if not raw_context:
            return f"No related database schema found"
        
        context = [item[0].page_content for item in raw_context]
        return context
    except Exception:
        return f"Got an error while fetching the database schema"

@tool
def execute_sql_query(sql_query: str)-> list:
    """
    Executes SQL query generated by LLM on SQl database.
    
    Args:
        sql_query: SQL query to execute on the database.
    
    Returns:
        Data in tuple format containing data return from rows.
    """
    try:
        connection = get_db_connection()
        cursor = connection.cursor(dictionary=True)
        cursor.execute(sql_query)
        data = cursor.fetchall()
        cursor.close()
        connection.close()
        
        if not data:
            return "Error while fetching data from database."
        
        return data
        
    except Exception:
        return "There is a problem while executing the query. The problem can be either you've generated wrong query or there is problem while connecting database."
    